version: '3.7'

services:
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CACHE_HOST: redis
    ports:
      - "8080:80"
    networks:
      - app_network
    deploy:
      replicas: 2
    volumes:
      - wordpress_data:/var/www/html

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

networks:
  app_network:

volumes:
  wordpress_data:
  db_data:
